# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kategoriEkl.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(301, 119)
        self.ekle = QtWidgets.QPushButton(Form)
        self.ekle.setGeometry(QtCore.QRect(100, 80, 101, 27))
        self.ekle.setObjectName("ekle")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 40, 267, 29))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.kategoriAdi = QtWidgets.QLineEdit(self.widget)
        self.kategoriAdi.setObjectName("kategoriAdi")
        self.horizontalLayout.addWidget(self.kategoriAdi)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ekle.setText(_translate("Form", "Kategori ekle"))
        self.label.setText(_translate("Form", "Ürün kategori adı"))
