# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(292, 173)
        self.pbGiris = QtWidgets.QPushButton(Form)
        self.pbGiris.setGeometry(QtCore.QRect(100, 120, 88, 27))
        self.pbGiris.setObjectName("pbGiris")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(40, 50, 231, 64))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.leKAdi = QtWidgets.QLineEdit(self.widget)
        self.leKAdi.setObjectName("leKAdi")
        self.verticalLayout.addWidget(self.leKAdi)
        self.leSifre = QtWidgets.QLineEdit(self.widget)
        self.leSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.leSifre.setObjectName("leSifre")
        self.verticalLayout.addWidget(self.leSifre)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pbGiris.setText(_translate("Form", "giriş"))
        self.label.setText(_translate("Form", "kullanıcı adı"))
        self.label_2.setText(_translate("Form", "şifre"))
