# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urunEkle_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 428)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 311, 351))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 66, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 66, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(15, 100, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 66, 19))
        self.label_4.setObjectName("label_4")
        self.ekle = QtWidgets.QPushButton(self.groupBox)
        self.ekle.setGeometry(QtCore.QRect(100, 300, 88, 27))
        self.ekle.setObjectName("ekle")
        self.urunAdi = QtWidgets.QLineEdit(self.groupBox)
        self.urunAdi.setGeometry(QtCore.QRect(96, 32, 142, 27))
        self.urunAdi.setObjectName("urunAdi")
        self.miktari = QtWidgets.QLineEdit(self.groupBox)
        self.miktari.setGeometry(QtCore.QRect(96, 65, 142, 27))
        self.miktari.setObjectName("miktari")
        self.kategorisi = QtWidgets.QComboBox(self.groupBox)
        self.kategorisi.setGeometry(QtCore.QRect(96, 98, 86, 27))
        self.kategorisi.setObjectName("kategorisi")
        self.aciklama = QtWidgets.QTextEdit(self.groupBox)
        self.aciklama.setGeometry(QtCore.QRect(96, 131, 183, 158))
        self.aciklama.setObjectName("aciklama")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 370, 24))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.urunListele = QtWidgets.QAction(MainWindow)
        self.urunListele.setObjectName("urunListele")
        self.kategoriEkle = QtWidgets.QAction(MainWindow)
        self.kategoriEkle.setObjectName("kategoriEkle")
        self.menuDosya.addAction(self.urunListele)
        self.menuDosya.addAction(self.kategoriEkle)
        self.menubar.addAction(self.menuDosya.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Ürün ekle"))
        self.label.setText(_translate("MainWindow", "Ürün adı"))
        self.label_2.setText(_translate("MainWindow", "Miktarı"))
        self.label_3.setText(_translate("MainWindow", "kategorisi"))
        self.label_4.setText(_translate("MainWindow", "Açıklama"))
        self.ekle.setText(_translate("MainWindow", "Ekle"))
        self.menuDosya.setTitle(_translate("MainWindow", "Dosya"))
        self.urunListele.setText(_translate("MainWindow", "Ürün listele"))
        self.kategoriEkle.setText(_translate("MainWindow", "Kategori ekle"))
